In [1]:
import numpy as np

For refence purposes, the following 100 numpy exercises will aid in understanding the use of numpy  - 
https://www.kaggle.com/code/utsav15/100-numpy-exercises

In [3]:
a = np.array([2, 4])

In [6]:
print (np.__version__)
np.show_config

2.1.2


<function numpy.__config__.show(mode='stdout')>

In [14]:
#creating a null vector of size 10
A = np.zeros(10)
#print(A)

#finding memory size of any array
Z = np.zeros((10,13))
print("%d bytes" % (Z.size*Z.itemsize))

1040 bytes


In [22]:
# creating a vector with values ranging 10 to 49
B = np.arange(10, 50)
print(B)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [23]:
#reverses the vector to start from the last digit
C = B[::-1]
print(C)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Matrices using Numpy

In [28]:
#creating a 3x3 matrix with values ranging from()
D = B.reshape(3,3)

ValueError: cannot reshape array of size 40 into shape (3,3)

In [30]:
#creating a 5x8 matrix with values ranging from()
D = B.reshape(5,8)
print(D)

[[10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49]]


non-zero elements

In [32]:
#an array may be as follows [1,2,0,0,4,0], to find theh indices of non-zero elements, the code will look as follows:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)
